- bower.json
- package.json
Gruntfile.js was not a valid entry point and was breaking browserify.
> point bower/npm etc. at the latest packaged cola.v3.min.js

- bower.json
- package.json
CommonJS support is still not there (see #44), but we should at least have `bower.json` and `package.json` in sync.
cf91f81 put the version numbers out of sync, and the fix in 1cf5dcc came after 3.1.0.
See https://github.com/tgdwyer/WebCola/issues/100 for more info.
> Bump bower.json and package.json to 3.1.1

- WebCola/src/gridrouter.ts
- WebCola/src/powergraph.ts
This pull request contains three fixes:
* The JavaScript `sort()` function is stable in Firefox/IE, but not in Chrome. This resulted in different behaviour for those browsers.
* There was a missing case in `orderEdges()` in the grid router, causing out-of-bounds array accesses, which resulted in an error.
* Edges that were reversed by the grid router (`routeEdges()`) were not reversed back again.
> Fixes in the power graph layout

- Gruntfile.js
On case-sensitive file systems, like Linux, tests would fail because `webcola/` and `WebCola/` became separate directories.
> Fix path names for case-sensitive file systems

- WebCola/examples/cygenegene.css
- WebCola/examples/cygenegene.html
- WebCola/index.html
Hi Tim -- This should fix the issue regarding the adaptor error in https://github.com/tgdwyer/WebCola/pull/125 .  I think the website must be using a version of Cola.js prior to my adding back the `cola.adaptor`.  Now, the example uses a snapshot of `cola.js` from the Cytoscape.js public source URLs.  It also adds the links on the demos etc.  -Max
> Addresses Cytoscape.js/Cola.js demo issues etc.

- WebCola/src/rectangle.ts
Chrome fails with an assertion failure in generateContraints() in rectangle.ts, because scanline is not empty at the end of the function. That's because the events get out of order and closes come before opens.
The code works OK in Firefox and IE, I think because their sort function is stable, so the open/close event pairs are kept in order.
> Fix assertion failure in Chrome

- WebCola/src/layout.ts
Here's half of a fix for #134. I've tested it with a simple dummy application but I can also add automated tests if that's helpful.
I did not check in the artifacts; not sure what you prefer @tgdwyer.
The other half of my fix for #134 is a start at some general API documentation here:
https://github.com/tgdwyer/WebCola/wiki/General-API-notes
Please review. Thanks!
Explanation (from the commit message): edge source and target can be specified by integer index or by reference to the node objects. if specified by reference, cola.js needs the node objects to have an `index` member specifying the integer index.
it is already initializing this from the position in the array but it needs to do this before calling the linkLengthCalculator; otherwise lengths will not be applied.
> set node index before it's needed

- WebCola/cola.js
In our project, which must support older browser versions , a bug occurs: 
"<i>Object doesn't support assert</i>"
At https://developer.mozilla.org/en-US/docs/Web/API/console/assert it states: 
"<i>This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.</i>"
> commented console asserts which may cause instabilities

- WebCola/src/layout.ts
D3 supports both references and number indexes for nodes and links. Webcola should have the same behavior for groups. This trivial patch fixes it.
> Support references when setting groups

- WebCola/.npmignore
Webcola is currently a ~20MB tarball; removing these folders from the
package shrinks that to ~225KB.
See
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
for documentation.
Note: There are likely other files currently in the package that should be
ignored, but these seemed to be obvious "low-hanging fruit".
Another alternative would be to use the `files` key in `package.json`;
that is a whitelist approach rather than a blacklist.
> Add a .npmignore to shrink NPM package size

- README.md
npm installs the module as `webcola`, so the dependency name should match, otherwise `npm install` will warn of an extraneous `webcola` module.
This issue was first observed in #203.
> fix npm installation instructions

- WebCola/examples/browsemovies.html
It is being called from `getNode`. The extra-call resulted in a duplicated node for the original movie - it's easy to see using a movie with a few casts, like [#17609](https://www.themoviedb.org/movie/17609-antichrist) for example.
> Removing a redundant call to addViewNode

- .npmignore
- README.md
- package.json
I have:
- Created `.npmignore` , which must differ from the `.gitignore` as in **not** ignoring the transcribed `.js` files.
- Updated the `README`, since now directly installing the package from the repo will result in errors due to the lack of transcribed `.js` files directly in the repo.
- Bumped the version number
**IMPORTANT**: The package still needs to be published to NPM and then one can test if the `.js` files are present in the `src` folder, as suggested in #211 .
> Proposed fix for #211

- .npmignore
doc/ is making the npm package huge (251 megs uncompressed!) and it isn't needed in the npm package. It looks like the .npmignore file tried to address this with `WebCola/doc`, but that directory isn't created. I believe it was intended to be `doc/`
> in .npmignore change WebCola/doc to doc/

- WebCola/src/layout.ts
Layout methods set defaults for optional params (e.g., x and y on any nodes passed in are set relative to the canvas if not defined). The types now reflect this optionality!
> fix(typings): add type support for cola arguments with optional params

- package.json
Moves dependencies that were only used in examples to devDependencies since they shouldn't be in the npm package. These were needlessly bloating my app.
> move dependencies not needed in npm package

- WebCola/test/tests.ts
Tim,
Being an idiot I assumed that nodes couldn't have duplicate labels.  I assumed that node {name:"a", group:1} and {name:"a",group:1} would be treated as the same node.  This is not the case.  I've added a test case to document the fact that duplicate node labels are allowed.
Vinaka vaka levu
-- 
Aidan
> Test to show that we allow duplicate node labels

- tsconfig.json
When running npm install I got an error complaining about missing
dist/src/adaptor.js file. Only the output of transpiling
Webcola/index.ts was present in the dist folder. And it wasn't bundled
so index.js contained require references to ./src/adaptor and others.
This change seems to fix this problem. The files that appear in the npm
version will appear in dist when building. I'm still puzzled by how it
could work for anyone else without this.
> Toolchain fix - missing referenced files in dist folder

- Gruntfile.js
- WebCola/src/handledisconnected.ts
- WebCola/src/layout.ts
- package.json
This should fix #244. It adds another optional parameter to `simulation.start()` though. Perhaps we should consider adding an options object as parameter instead of additional parameters?
> Allow restarting without re-centering graph

- WebCola/src/geom.ts
In some occasions lines are crossing nodes.
The visibilitygraph shows the problem. There is a line crossing a boundary.
There was and index issue, causing the last vertices were not taken into account.
After the fix, the visibilitygraph seems correct.
Signed-off-by: Henk Westhuis <henk.westhuis@ultimo.com>
> Fix determining tangents for visibility graph

- WebCola/src/layout.ts
`Group` padding is not needed to be set as it is defaulted to 1, however the typescript type makes it required, which is not necessary.
See https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L235 for where it is defaulted.
> Update Group typescript interface: set padding to be optional

- package.json
WebCola has UMD builds, which is great! This adds `unpkg` and `jsdelivr` fields, so that tools like d3-require and requirejs can easily require these builds - this means that if you depend on `https://unpkg.com/webcola@3`, you'll depend on the UMD build, instead of being redirected to the CommonJS `index.js` file.
> Add unpkg and jsdelivr fields to point to UMD

- WebCola/src/layout.ts
Now the previous group position (function of `bounds`) is maintained. This results in a more stable layout.
Fixes https://github.com/tgdwyer/WebCola/issues/286
> Fixed issue where groups drift towards 0, 0 with every call to Start

- WebCola/src/gridrouter.ts
Unrelated to the issue, but I ran into an infinite loop when building a graph in https://github.com/tgdwyer/WebCola/issues/291 that had only one column:
Root cause was `this.edges` had `NaN` x and y coordinates because row / column midpoints were incorrectly calculated. In this PR, correctly calculating midpoints when there is only one row/column.
> FIX: fixing infinite loop / NaN length for edges when only one column/row in grid router

- src/layout.ts
- src/linklengths.ts
This facilitates the use of WebCoLa for newcomers who want to learn by trying out the various options.
Having an Array<any> leaves you in the dark about how these constraints look, without looking at various places (the website examples, the constraints wiki page, issues, ...).
Some open questions remain:
- is the optionality of all the properties set correctly?
- is it correct to restrict properties where nodes are expected to just number type? It seems like for group constraints, numbers are replaced with the respective node and other types are not transformed, so setting nodes directly may also work there. But i could not find anything that transforms the numbers into nodes for the constraints...
Maybe someone can give insight into these questions.
> Add proper typing for constraints array
